language: ruby
rvm:
  - 2.1.3

sudo: false

cache: bundler

before_script:
  - bundle config build.nokogiri --use-system-libraries
  - mv config/database.cc.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:schema:load

script: bundle exec rake test
