language: ruby
rvm:
  - 1.9.3
before_install:
  - bundle config build.nokogiri --use-system-libraries
script:
  - mv config/database.cc.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake test
