language: ruby

rvm:
  - 2.1.6

addons:
  postgresql: "9.3"

sudo: false

cache: bundler

env:
  - DISPLAY=":99.0"

before_script:
  - sh -e /etc/init.d/xvfb start
  
script: bundle exec rake teaspoon
