language: ruby
rvm:
  - 2.1.2
  #MERGENOTE - error loading schema with 1.9.3 - we will look into this later
env:
  - SUITE="units"
  - SUITE="functionals"
  - SUITE="integration"
before_install:
  - bundle config build.nokogiri --use-system-libraries
script:
  - mv config/database.cc.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake test:$SUITE
