language: ruby

rvm:
  - 2.1.6

addons:
  postgresql: "9.3"

sudo: false

cache: bundler

env:
  - DISPLAY=":99.0" DB_TYPE=mysql

before_script:
  - sh -e /etc/init.d/xvfb start
  - cp test/database.travis.$DB_TYPE.yml config/database.yml
  
script: bundle exec rake teaspoon
