version: '2'
services:
  db: # Database implementation, in this case MySQL
    image: mysql:5.7
    restart: always
    env_file:
      - docker/db.env
    volumes:
      - mysql-db:/var/lib/mysql

  seek: # The SEEK application, passenger, solr and delayed_job worker
    build: .
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
    env_file:
      - docker/db.env
    volumes:
      - seek-filestore:/home/app/seek/filestore
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db

volumes:
  seek-filestore:
    external: true
  mysql-db:
    external: true
