--- 
- title: JWS Online
  url: https://fair-dom.org/jws-online/
  logo: /assets/front_page/integrations_JWS.png
- title: openBIS
  url: https://seek4science.org/organise.html
  logo: /assets/front_page/openBIS_Logo.png
- title: rightfield
  url: https://fair-dom.org/platform/rightfield/
  logo: /assets/front_page/integrations_rightfield.png