Bacillus_subtilis_Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_1423"
  conceptable: Bacillus_subtilis(Organism)

Clostridium acetobutylicum Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_1488"
  conceptable: Clostridium acetobutylicum(Organism)

Escherichia coli Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_562"
  conceptable: Escherichia coli(Organism)

Enterococcus faecalis Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_1351"
  conceptable: Enterococcus faecalis(Organism)

Streptococcus pyogenes Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_1314"
  conceptable: Streptococcus pyogenes(Organism)

Pseudomonas putida Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_303"
  conceptable: Pseudomonas putida(Organism)

Pseudomonas fluorescens Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_294"
  conceptable: Pseudomonas fluorescens(Organism)

Saccharomyces cerevisiae Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_4932"
  conceptable: Saccharomyces cerevisiae(Organism)

Streptomyces coelicolor Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_1902"
  conceptable: Streptomyces coelicolor(Organism)

Sulfolobus solfataricus Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_2287"
  conceptable: Sulfolobus solfataricus(Organism)

Trypanosoma brucei Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_5691"
  conceptable: Trypanosoma brucei(Organism)

Lactobacillus plantarum Concept:
  ontology_id: "NCBITAXON"
  concept_uri: "http://purl.obolibrary.org/obo/NCBITaxon_1590"
  conceptable: Lactobacillus plantarum(Organism)