technology:
  title: technology
  children: binding,chromatography, culture_growth,electrophoresis,imaging,Mass_Spectrometry,microarray,PCR,structural_methods
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#TechnologyType

binding:
  title: binding
  children: 2-hybrid_system,surface_plasmon_resonance
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#binding

2-hybrid_system:
  title: 2-hybrid system
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#2-hybrid_system

surface_plasmon_resonance:
  title: surface plasmon resonance
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#surface_plasmon_resonance

chromatography:
  title: chromatography
  children: gas_chromatography,HPLC,UPLC
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#chromatography

gas_chromatography:
  title: gas chromatography
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#gas_chromatography

HPLC:
  title: HPLC
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#HPLC

UPLC:
  title: UPLC
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#UPLC

electrophoresis:
  title: electrophoresis
  children: capillary_electrophoresis,gel_electrophoresis
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#electrophoresis

capillary_electrophoresis:
  title: capillary electrophoresis
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#capillary_electrophoresis

gel_electrophoresis:
  title: gel electrophoresis
  children: 2D_gel_electrophoresis,SDS_PAGE
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#gel_electrophoresis

2D_gel_electrophoresis:
  title: 2D gel electrophoresis
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#2D_gel_electrophoresis
  
SDS_PAGE:
  title: SDS PAGE
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#SDS_PAGE

imaging:
  title: imaging
  children: FRAP
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#imaging

FRAP:
  title: FRAP
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#FRAP

Mass_Spectrometry:
  title: mass spectrometry
  children: Accelerator_Mass_Spectrometry,Gas_Chromatography_Mass_Spectrometry,Inductively_Coupled_Plasma_Mass_Spectrometry,Ion_Mobility_Spectrometry_Mass_Spectrometry,Isotope_Ratio_Mass_Spectrometry,liquid_chromatography-tandem_mass_spectrometry,liquid_chromatography_Mass_Spectrometry,MALDI_TOF,SELDI_TOF,Tandem_Mass_Spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#mass_Spectrometry

Accelerator_Mass_Spectrometry:
  title: accelerator mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Accelerator_Mass_Spectrometry

Gas_Chromatography_Mass_Spectrometry:
  title: gas chromatography mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Gas_Chromatography_Mass_Spectrometry

Inductively_Coupled_Plasma_Mass_Spectrometry:
  title: inductively coupled plasma mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Inductively_Coupled_Plasma_Mass_Spectrometry

Ion_Mobility_Spectrometry_Mass_Spectrometry:
  title: ion mobility spectrometry mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Ion_Mobility_Spectrometry_Mass_Spectrometry

Isotope_Ratio_Mass_Spectrometry:
  title: isotope ratio mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Isotope_Ratio_Mass_Spectrometry

liquid_chromatography-tandem_mass_spectrometry:
  title: liquid chromatography-tandem mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#liquid_chromatography-tandem_mass_spectrometry

liquid_chromatography_Mass_Spectrometry:
  title: liquid chromatography mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#liquid_chromatography_Mass_Spectrometry

MALDI_TOF:
  title: MALDI TOF
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#MALDI_TOF

SELDI_TOF:
  title: SELDI TOF
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#SELDI_TOF

Tandem_Mass_Spectrometry:
  title: tandem mass spectrometry
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#Tandem_Mass_Spectrometry


microarray:
  title: microarray
  children: ChIP-on-chip,custom_Array,DNA_Methylation,miRNA_microarray
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#microarray

#cDNA_microarray:
#  title: cDNA microarray
#  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#

ChIP-on-chip:
  title: ChIP-on-chip
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#ChIP-on-chip

custom_Array:
  title: custom array
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#custom_Array

DNA_Methylation:
  title: DNA methylation
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#DNA_Methylation

miRNA_microarray:
  title: miRNA microarray
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#miRNA_microarray

PCR:
  title: PCR
  children: qPCR,qRT-PCR
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#PCR

qPCR:
  title: qPCR
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#qPCR

qRT-PCR:
  title: qRT-PCR
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#qRT-PCR


structural_methods:
  title: structural methods
  children: NMR
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#structural_methods

NMR:
  title: NMR
  term_uri: http://www.mygrid.org.uk/ontology/JERMOntology#NMR