cwl_workflow_class:
  id: 1
  title: <%= I18n.t('workflows.cwl_workflow') %>
  key: CWL

galaxy_workflow_class:
  id: 2
  title: <%= I18n.t('workflows.galaxy_workflow') %>
  key: GALAXY

knime_workflow_class:
  id: 3
  title: <%= I18n.t('workflows.knime_workflow') %>
  key: KNIME

ro_workflow_class:
  id: 4
  title: <%= I18n.t('workflows.ro_workflow') %>
  key: RO