# See the explanation in faceted_browsing.yml

project:
    label: Project
    value_from: projects:title
    rails_class: Project

created_at:
    label: Created In
    value_from: created_at:year

contributor:
    label: Contributor
    value_from: contributor:person:name

tag:
    label: Tag
    value_from: tags_as_text_array