Assay:
  organism:
      label: Organism
      value_from: organisms:title
  project:
      label: Project
      value_from: projects:title
  created_at:
      label: Created At
      value_from: created_at:year
      facet_class: NumericRange
      interval: 1
  assay_type:
      label: Assay Type
      value_from: assay_type_label
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::AssayTypeReader,Seek::Ontologies::ModellingAnalysisTypeReader
  technology_type:
      label: Technology Type
      value_from: technology_type_label
      facet_class: Exhibit.HierarchicalFacet
      tree_from: Seek::Ontologies::TechnologyTypeReader


Model:
  project:
      label: Project
      value_from: projects:title
  model_type:
      label: Model Type
      value_from: model_type:title
  model_format:
      label: Model Format
      value_from: model_format:title
  recommended_environment:
      label: Execution or Visualization Environment
      value_from: recommended_environment:title