project:
    label: Project
    value_from: projects:title
    rails_class: Project

created_at:
    label: Created In
    value_from: created_at:year

tag:
    label: Tag
    value_from: tags_as_text_array

author:
    label: Author
    value_from: publication_author_names