# External API keys
external_api_keys: &external_api_keys
  elixir_aai:
    client_id: ""
    secret: ""

development:
  <<: *external_api_keys
  secret_key_base: a

test:
  <<: *external_api_keys
  secret_key_base: a

production:
  <<: *external_api_keys
  secret_key_base: <%= Seek::Config.secret_key_base %>
