# External API keys
external_api_keys: &external_api_keys

development:
  <<: *external_api_keys
  secret_key_base: a

test:
  <<: *external_api_keys
  secret_key_base: a

production:
  <<: *external_api_keys
  secret_key_base: <%= Seek::Config.secret_key_base %>
