#change settings where appropriate, and then save as virtuoso_settings.yml

uri: http://localhost:8890/sparql
update_uri: http://localhost:8899/sparql-auth

username: username
password: password

private_graph: seek:private
public_graph: seek:public