name: ansible-install
run-name: ${{ github.actor }} is testing Ansible install
on:
  push:
    branches:
      - ansible
  workflow_dispatch:

jobs:
  install-seek-from-ansible:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04,ubuntu-22.04,ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get barings
        run: |
          pwd
          ls

      - name: Configure ansible for local install
        run: |
          sed -i '/vault_password_file/d' /home/runner/work/seek/seek/script/ansible/ansible.cfg
          sed -i '/ssh_connection/d' /home/runner/work/seek/seek/script/ansible/ansible.cfg
          sed -i '/pipelining/d' /home/runner/work/seek/seek/script/ansible/ansible.cfg
          sed -i 's/\- hosts\: \[servers\]/\- hosts\: localhost/g' /home/runner/work/seek/seek/script/ansible/Deploy-SEEK.yml
          sed -i '/\- hosts\: localhost/a \ \ connection\: local' /home/runner/work/seek/seek/script/ansible/Deploy-SEEK.yml
          sed -i 's/user_var\: francisco/user_var\: runner/' /home/runner/work/seek/seek/script/ansible/group_vars/vars.yml
          sed -i 's/git_dest\: \/home\/francisco/git_dest\: \/home\/runner\/work\/seek/' /home/runner/work/seek/seek/script/ansible/group_vars/vars.yml
          sed -i 's/sql_user\: francisco/sql_user\: mysqluser/' /home/runner/work/seek/seek/script/ansible/group_vars/vars.yml
          sed -i '/sql_user\: mysqluser/a sql_password: mysqlpassword' /home/runner/work/seek/seek/script/ansible/group_vars/vars.yml

      - name: Get barings
        run: |
          pwd
          ls
          ls /home/runner/work
          ls /home/runner/work/seek
          ls /home/runner/work/seek/seek


      - name: Install SEEK through ansible
        run: ansible-playbook Deploy-SEEK.yml
