name: ansible-install
run-name: "Testing Ansible install after commit \"${{ github.event.head_commit.message }}\""
on:
  push:
    branches:
      - ansible
  workflow_dispatch:

jobs:
  install-seek-from-ansible:
    runs-on: ${{matrix.os}}
    #continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-20.04,ubuntu-22.04,ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure ansible for local install
        working-directory: /home/runner/work/seek/seek/script/ansible/
        run: |
          sed -i '/vault_password_file/d' ansible.cfg
          sed -i '/ssh_connection/d' ansible.cfg
          sed -i '/pipelining/d' ansible.cfg
          sed -i 's/\- hosts\: \[servers\]/\- hosts\: localhost/g' Deploy-SEEK.yml
          sed -i '/\- hosts\: localhost/a \ \ connection\: local' Deploy-SEEK.yml
          sed -i 's/user_var\: username/user_var\: runner/' group_vars/vars.yml
          sed -i 's/git_dest\: \/home\/username/git_dest\: \/home\/runner\/work/' group_vars/vars.yml
          sed -i '/sql_user\: sql_username/a sql_password: mysqlpassword' group_vars/vars.yml

      - name: Prepares system for ansible install
        run: |
          sudo apt install acl -y

      - name: Install SEEK through ansible
        working-directory: /home/runner/work/seek/seek/script/ansible/
        run: |
          ansible-playbook Deploy-SEEK.yml
